import { ElementRef, ViewRef, ViewContainerRef, ComponentFactoryResolver, OnInit, OnChanges, AfterViewInit, OnDestroy, EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { Subscription } from 'rxjs';
import { FateControllerService } from '../fate-controller.service';
import { FateHtmlParserService } from '../fate-html-parser.service';
import { FateParserService } from '../fate-parser.service';
export declare class FateInputComponent implements ControlValueAccessor, OnChanges, OnInit, AfterViewInit, OnDestroy {
    protected el: ElementRef;
    protected controller: FateControllerService;
    protected htmlParser: FateHtmlParserService;
    protected parser: FateParserService;
    protected sanitizer: DomSanitizer;
    protected factoryResolver: ComponentFactoryResolver;
    uiId: string;
    row: number;
    customClass: string;
    placeholder: string;
    focus: EventEmitter<void>;
    blur: EventEmitter<void>;
    viewContainerRef: ViewContainerRef;
    protected dropdownComponent: ViewRef;
    protected dropdownInstance: any;
    dropdownPostionTop: string;
    dropdownPostionLeft: string;
    inlineAction: any;
    content: SafeHtml;
    empty: boolean;
    protected editTarget: any;
    protected isFocused: boolean;
    constructor(el: ElementRef, controller: FateControllerService, htmlParser: FateHtmlParserService, parser: FateParserService, sanitizer: DomSanitizer, factoryResolver: ComponentFactoryResolver);
    private reactToChanges;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnChanges(changes: any): void;
    ngOnDestroy(): void;
    protected computeHeight(): void;
    protected checkEmpty(): void;
    protected getHeight(rowCount: any): string;
    protected uiSubscription: Subscription;
    protected subscribeToUi(uiId: any): void;
    protected selectionRange: Range;
    protected saveSelection(): void;
    protected restoreSelection(): void;
    protected selectionInEditableTarget(): boolean;
    protected detectStyle(): void;
    protected changed: ((value: string) => void)[];
    writeValue(value: string): void;
    registerOnChange(fn: (value: string) => void): void;
    registerOnTouched(fn: () => void): void;
    protected checkForDropdownContext(): void;
    protected initDropdown(actionComponent: any, position: any): void;
    protected updateDropdown(value: any): void;
    protected updateDropdownPosition(): void;
}
